flash_sale/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(apps.get_app_config('oscar').urls[0])),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/offer/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from oscar.apps.offer.abstract_models import AbstractConditionalOffer, AbstractBenefit
from oscar.core.loading import get_class


class ConditionalOffer(AbstractConditionalOffer):
    SITE, FLASH_SALE, VOUCHER, USER, SESSION = "Site", "Flash Sale", "Voucher", "User", "Session"
    TYPE_CHOICES = (
        (SITE, _("Site offer - available to all users")),
        (FLASH_SALE, _("Flash Sale offer - short-term discount for the specific product")),
        (VOUCHER, _("Voucher offer - only available after entering the appropriate voucher code")),
        (USER, _("User offer - available to certain types of user")),
        (SESSION, _("Session offer - temporary offer, available for a user for the duration of their session")),
    )
    offer_type = models.CharField(_("Type"), choices=TYPE_CHOICES, default=SITE, max_length=128)


class Benefit(AbstractBenefit):
    PERCENTAGE, FIXED, MULTIBUY, FIXED_PRICE, FIXED_PER_PRODUCT = (
        "Percentage", "Absolute", "Multibuy", "Fixed price", "Fixed per product")
    SHIPPING_PERCENTAGE, SHIPPING_ABSOLUTE, SHIPPING_FIXED_PRICE = (
        'Shipping percentage', 'Shipping absolute', 'Shipping fixed price')

    TYPE_CHOICES = (
        (PERCENTAGE, _("Discount is a percentage off of the product's value")),
        (FIXED, _("Discount is a fixed amount off of the product's value")),
        (FIXED_PER_PRODUCT, _("Discount is a fixed amount off of each product's value that match condition")),
        (MULTIBUY, _("Discount is to give the cheapest product for free")),
        (FIXED_PRICE,
         _("Get the products that meet the condition for a fixed price")),
        (SHIPPING_ABSOLUTE,
         _("Discount is a fixed amount of the shipping cost")),
        (SHIPPING_FIXED_PRICE, _("Get shipping for a fixed price")),
        (SHIPPING_PERCENTAGE, _("Discount is a percentage off of the shipping"
                                " cost")),
    )
    type = models.CharField(_("Type"), max_length=128, choices=TYPE_CHOICES, blank=True)

    def apply_to_product(self, price):
        if self.type in [self.PERCENTAGE, self.FIXED_PRICE, self.FIXED_PER_PRODUCT]:
            return self.proxy().apply_to_product(price)

    @property
    def proxy_map(self):
        custom_proxy_map = super().proxy_map
        custom_proxy_map[self.PERCENTAGE] = get_class('offer.benefits', 'CustomPercentageDiscountBenefit')
        custom_proxy_map[self.FIXED_PRICE] = get_class('offer.benefits', 'CustomFixedPriceBenefit')
        custom_proxy_map[self.FIXED_PER_PRODUCT] = get_class(
            'offer.benefits', 'CustomAbsoluteDiscountPerProductBenefit'
        )
        return custom_proxy_map


from oscar.apps.offer.models import *  # noqa isort:skip
from .benefits import *  # noqa isort:skip

apps/dashboard/offers/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from oscar.core.loading import get_model
from oscar.forms import widgets


Benefit = get_model('offer', 'Benefit')


class FlashSaleForm(forms.Form):
    TYPE_CHOICES = (
        (Benefit.PERCENTAGE, _("Discount is a percentage off of the product's value")),
        (Benefit.FIXED_PRICE, _("Get the products that meet the condition for a fixed price")),
        (Benefit.FIXED_PER_PRODUCT, _("Discount is a fixed amount off of each product's value that match condition")),
    )

    start_datetime = forms.DateTimeField(
        widget=widgets.DateTimePickerInput(), label=_("Start date"), required=False)
    end_datetime = forms.DateTimeField(
        widget=widgets.DateTimePickerInput(), label=_("End date"), required=False)
    benefit_type = forms.ChoiceField(choices=TYPE_CHOICES)
    benefit_value = forms.DecimalField()

apps/dashboard/offers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView

from oscar.core.loading import get_model

from .forms import FlashSaleForm


Product = get_model('catalogue', 'Product')
Range = get_model('offer', 'Range')
Condition = get_model('offer', 'Condition')
ConditionalOffer = get_model('offer', 'ConditionalOffer')
Benefit = get_model('offer', 'Benefit')


class FlashSaleCreateView(FormView):
    form_class = FlashSaleForm
    template_name = 'oscar/dashboard/offers/flash_sale_form.html'

    def dispatch(self, request, *args, **kwargs):
        product_pk = self.kwargs.get('product_pk', None)
        self.product = get_object_or_404(Product, pk=product_pk)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        benefit_type = form.cleaned_data['benefit_type']
        benefit_value = form.cleaned_data['benefit_value']
        start_datetime = form.cleaned_data['start_datetime']
        end_datetime = form.cleaned_data['end_datetime']
        range_name = 'Product range for product "%s(#%s)"' % (self.product.get_title(), self.product.pk)
        product_range, created = Range.objects.get_or_create(name=range_name)
        if created:
            product_range.add_product(self.product)

        condition = Condition.objects.create(range=product_range, type=Condition.COUNT, value=1)
        benefit = Benefit.objects.create(range=product_range, type=benefit_type, value=benefit_value)
        offer_name = 'Flash sale for product "%s(#%s)" from %s till %s' % (
            self.product.get_title(),
            self.product.pk,
            start_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            end_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        )
        offer = ConditionalOffer.objects.create(
            name=offer_name, offer_type=ConditionalOffer.FLASH_SALE, condition=condition, benefit=benefit,
            start_datetime=start_datetime, end_datetime=end_datetime
        )
        url = reverse_lazy('dashboard:offer-detail', args=(offer.pk,))
        return HttpResponseRedirect(url)

templates/oscar/catalogue/partials/gallery.html
{% load image_tags %}
{% load i18n %}
{% load staticfiles %}
{% load flash_sale_tags %}

{% with all_images=product.get_all_images %}
    {# use length rather then count as the images get queried anyways #}

    {% if all_images|length > 1 %}

        <div id="product_gallery" class="carousel slide">

            <div class="thumbnail">
                <div class="carousel-inner" role="listbox">

                {% is_product_on_sale product as is_on_sale %}
                {% if is_on_sale %}
                    {% include 'oscar/catalogue/partials/sale_icon.html' %}
                {% endif %}

                {% for image in all_images %}
                    <div class="item {% if forloop.first %}active{% endif %}">
                        {% oscar_thumbnail image.original "440x400" upscale=False as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control left" href="#product_gallery" role="button" data-slide="prev">
                    <span class="icon-prev fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-left fa-stack-1x"></i>
                    </span>
                </a>
                <a class="carousel-control right" href="#product_gallery" role="button" data-slide="next">
                    <span class="icon-next fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-right fa-stack-1x"></i>
                    </span>
                </a>
            </div>

            <ol class="carousel-indicators thumbnail">
                {% for image in all_images %}
                    <li data-target="#product_gallery" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}">
                        {% oscar_thumbnail image.original "65x55" crop="center" as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                    </li>
                {% endfor %}
            </ol>
        </div>

    {% else %}

        {# Only one image to show #}
        <div id="product_gallery" class="carousel">
            <div class="thumbnail">
                <div class="carousel-inner">

                    {% is_product_on_sale product as is_on_sale %}
                    {% if is_on_sale %}
                        {% include 'oscar/catalogue/partials/sale_icon.html' %}
                    {% endif %}

                    <div class="item active">
                    {% with image=product.primary_image %}
                        {% oscar_thumbnail image.original "440x400" upscale=False as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                    {% endwith %}
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endwith %}

templates/oscar/catalogue/partials/product.html
{% extends 'oscar/catalogue/partials/product.html' %}

{% load image_tags %}
{% load flash_sale_tags %}


{% block product_image %}

    {% is_product_on_sale product as is_on_sale %}
    {% if is_on_sale %}
        {% include 'oscar/catalogue/partials/sale_icon.html' with is_small=True %}
    {% endif %}

    <div class="image_container">
        {% with image=product.primary_image %}
            {% oscar_thumbnail image.original "x155" upscale=False as thumb %}
            <a href="{{ product.get_absolute_url }}">
                <img src="{{ thumb.url }}" alt="{{ product.get_title }}" class="thumbnail">
            </a>
        {% endwith %}
    </div>
{% endblock %}

templates/oscar/catalogue/partials/sale_icon.html
{% if is_small %}
    <div style="width: 50px; height: 50px; position: absolute; right: 0; top: 0; z-index: 2;">
{% else %}
    <div style="width: 96px; height: 96px; position: absolute; right: 0; top: 0; z-index: 2;">
{% endif %}
    {% include 'oscar/catalogue/partials/sale_icon.svg' %}
</div>

templates/oscar/catalogue/partials/stock_record.html
{% load currency_filters %}
{% load i18n %}
{% load purchase_info_tags %}
{% load flash_sale_tags %}

{% purchase_info_for_product request product as session %}

{% is_product_on_sale product as is_on_sale %}

{% if session.price.exists %}
    <p class="price_color">
        <span {% if is_on_sale %}style="color: silver; text-decoration: line-through"{% endif %}>
            {% if session.price.excl_tax == 0 %}
                {% trans "Free" %}
            {% elif session.price.is_tax_known %}
                {{ session.price.incl_tax|currency:session.price.currency }}
            {% else %}
                {{ session.price.excl_tax|currency:session.price.currency }}
            {% endif %}
        </span>
        {% if is_on_sale %}
            {% calculate_product_price_incl_discounts product session.price as sale_price %}
            {{ sale_price|currency:session.price.currency }}
        {% endif %}
    </p>
    <div style="font-size: 0.9em; margin-top:-10px;">
      {% if is_on_sale %}
         {% get_flash_sale_offer product as flash_sale_offer %}
          <b>Discount available till:</b><br>
         {{ flash_sale_offer.end_datetime|date:'Y-m-d H:i' }}
      {% endif %}
    </div>
{% else %}
    <p class="price_color">&nbsp;</p>
{% endif %}
<p class="{{ session.availability.code }} availability">
    <i class="icon-{% if session.availability.is_available_to_buy %}ok{% else %}remove{% endif %}"></i>
    {% if verbose %}
        {{ session.availability.message }}
    {% else %}
        {{ session.availability.short_message }}
    {% endif %}
</p>

templates/oscar/dashboard/catalogue/product_row_actions.html
{% load django_tables2 %}
{% load i18n %}
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
            {% trans "Actions" %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{% url 'dashboard:catalogue-product' pk=record.id %}{% querystring %}">{% trans "Edit" %}</a>
            </li>
            <li>
                <a href="{{ record.get_absolute_url }}"> {% trans "View on site" %}</a>
            </li>
            <li>
                <a href="{% url 'dashboard:catalogue-product-delete' pk=record.id %}">{% trans "Delete" %}</a>
            </li>
            <li>
              <a href="{% url 'dashboard:create-flash-sale' product_pk=record.id %}">{% trans "Create flash sale" %}</a>
            </li>
        </ul>
    </div>
</div>

templates/oscar/dashboard/offers/flash_sale_form.html
{% extends 'oscar/dashboard/layout.html' %}

{% load currency_filters %}

{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% trans "Create new flash sale" %} | {% trans "Offers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li>
        <a href="{% url 'dashboard:offer-list' %}">{% trans "Offers" %}</a>
    </li>
    <li>
        {% trans "Create new flash sale" %}
    </li>
</ul>
{% endblock %}

{% block headertext %}
  {% trans "Create new flash sale" %}
{% endblock %}

{% block dashboard_content %}
    <div class="row">
        <div class="{% if session_offer %}col-md-6{% else %}col-md-9{% endif %}">
            <form method="post" class="form-stacked wysiwyg fixed-actions">
                <div class="table-header">
                    <h3>Flash sale details</h3>
                </div>
                <div class="well">
                  {% include 'oscar/dashboard/partials/form.html' with includes_files=1 class='wysiwyg' %}
              </div>
            </form>
        </div>
    </div>
{% endblock dashboard_content %}

{% block onbodyload %}
    {{ block.super }}
    oscar.dashboard.offers.init();
{% endblock %}

templates/oscar/dashboard/offers/offer_list.html
{% extends 'oscar/dashboard/offers/offer_list.html' %}

{% load currency_filters %}
{% load sorting_tags %}
{% load i18n %}

{% block dashboard_content %}
    <div class="well">
        <form method="get" class="form-inline">
            {% include 'oscar/dashboard/partials/form_fields_inline.html' with form=form %}
            <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Searching...' %}">{% trans "Search" %}</button>
        </form>
    </div>

    <form method="post" class="order_table">
        {% csrf_token %}
        <table class="table table-striped table-bordered">
            <caption>
                <i class="icon-gift icon-large"></i>{{ queryset_description }}
                {% if is_filtered %}
                    <a href="{% url 'dashboard:offer-list' %}" >{% trans "Reset" %}</a>
                {% endif %}
            </caption>
            {% if offers %}
                <tr>
                    <th>{% anchor 'name' _('Offer name') %}</th>
                    <th>{% anchor 'type' _('Type') %}</th>
                    <th>{% anchor 'start_date' _('Start date') %}</th>
                    <th>{% anchor 'end_date' _('End date') %}</th>
                    <th>{% trans "Priority" %}</th>
                    <th>{% trans "Incentive" %}</th>
                    <th>{% trans "Condition" %}</th>
                    <th>{% trans "Is available?" %}</th>
                    <th>{% trans "Restrictions" %}</th>
                    <th>{% anchor 'num_applications' _('Uses') %}</th>
                    <th>{% anchor 'total_discount' _('Cost') %}</th>
                    <th></th>
                </tr>
                {% for offer in offers %}
                    <tr>
                        <td><a href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{{ offer.name }}</a></td>
                        <td>{{ offer.get_offer_type_display }}</td>
                        <td>{{ offer.start_datetime|default:"-" }}</td>
                        <td>{{ offer.end_datetime|default:"-" }}</td>
                        <td>{{ offer.priority }}</td>
                        <td>{{ offer.benefit.description|safe }}</td>
                        <td>{{ offer.condition.description|safe }}</td>
                        <td>{% if offer.is_available %}
                                <span class="label label-success">{% trans "Yes" %}</span>
                            {% else %}
                                <span class="label label-danger">{% trans "No" %}</span>
                            {% endif %}
                        </td>
                        <td>
                            {% for restriction in offer.availability_restrictions %}
                                {% if not restriction.is_satisfied %}
                                    <label class="label label-danger">
                                        {{ restriction.description }}
                                    </label>
                                {% else %}
                                    {{ restriction.description }}</br>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>{{ offer.num_applications }}</td>
                        <td>{{ offer.total_discount|currency }}</td>
                        <td>
                            <div class="btn-toolbar">
                                <div class="btn-group">
                                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                                        {% trans "Actions" %}
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a class="" href="{% url 'offer:detail' slug=offer.slug %}">{% trans "Browse" %}</a></li>
                                        <li><a class="" href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{% trans "Stats" %}</a></li>
                                        <li><a class="" href="{% url 'dashboard:offer-metadata' pk=offer.pk %}">{% trans "Edit" %}</a></li>
                                        <li><a class="" href="{% url 'dashboard:offer-delete' pk=offer.pk %}">{% trans "Delete" %}</a></li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr><td>{% trans "No offers found." %}</td></tr>
            {% endif %}
        </table>
        {% include "oscar/dashboard/partials/pagination.html" %}
    </form>
{% endblock dashboard_content %}